[app]
address = "0.0.0.0:9000"
admin_username = "${LISTMONK_ADMIN_USER}"
admin_password = "${LISTMONK_ADMIN_PASSWORD}"

[db]
host = "${PGHOST}"
port = 5432
user = "${PGUSER}"
password = "${PGPASSWORD}"
database = "${PGDATABASE}"
ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"
